services:
  tika:
    ports:
      - target: 9998
        published: 9998
        protocol: tcp
        mode: host
    image: apache/tika:latest-full
    deploy:
      resources:
        limits:
          memory: 8G
    networks:
      - teseo_net

  nifi:
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
    image: abrimostech/teseoetl:1.0.0
    hostname: nifi.teseodev1.abrimos.info
    environment:
      - TRUSTSTORE_PASSWORD=changeme-teseoetl-default-trustsotre-password!
      - TRUSTSTORE_TYPE=JKS
      - NIFI_WEB_PROXY_HOST=nifi.teseodev1.abrimos.info
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=teseoetl-default-password
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_REMOTE_INPUT_HOST=0.0.0.0
      - NIFI_CLUSTER_NODE_ADDRESS=0.0.0.0
      - HOSTNAME_OVERRIDE=0.0.0.0
      - NIFI_SENSITIVE_PROPS_KEY=teseoetl-sensitive-props-key
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER=single-user-provider
      - NIFI_SECURITY_USER_AUTHORIZER=single-user-authorizer
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER_CONFIGURATION_FILE=/opt/nifi/nifi-current/conf/login-identity-providers.xml
      - INITIAL_ADMIN_IDENTITY=admin
      - NIFI_SECURITY_IDENTITY_MAPPING_PATTERN_KERB=^(.*?)/instance@(.*?)$$
      - NIFI_SECURITY_IDENTITY_MAPPING_VALUE_KERB=$$1@$$2
      - NIFI_SECURITY_IDENTITY_MAPPING_TRANSFORM_KERB=UPPER
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER_GENERATED_USERNAME=
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER_GENERATED_PASSWORD=
    deploy:
      resources:
        limits:
          memory: 8G
    volumes:
      - type: bind
        source: ./nifi/certs
        target: /opt/nifi/nifi-current/certs
      - type: bind
        source: ./nifi/conf
        target: /opt/nifi/nifi-current/conf
      - type: bind
        source: ./nifi/flowfile_repository
        target: /opt/nifi/nifi-current/flowfile_repository
      - type: bind
        source: ./nifi/provenance_repository
        target: /opt/nifi/nifi-current/provenance_repository
      - type: bind
        source: ./nifi/logs
        target: /opt/nifi/nifi-current/logs
      - type: bind
        source: ./nifi/state
        target: /opt/nifi/nifi-current/state
      - type: bind
        source: ./teseo_scripts
        target: /opt/teseo_scripts
      - type: bind
        source: ./teseo_files
        target: /opt/teseo_files
    networks:
      - teseo_net

networks:
  teseo_net:
    driver: overlay
    attachable: true
