# Enable detailed logging
#plugins.security.audit.config.log_request_body: true
plugins.security.audit.config.resolve_indices: true
plugins.security.audit.config.resolve_bulk_requests: true
plugins.security.audit.config.exclude_sensitive_headers: true
# Log all categories
plugins.security.audit.config.disabled_rest_categories: NONE
plugins.security.audit.config.disabled_transport_categories: NONE

# Enable specific audit events
plugins.security.audit.config.enable_rest: true
plugins.security.audit.config.enable_transport: true
<<<<<<< HEAD
=======

>>>>>>> bf1ecf27eb111f7417395cc18f99eb8e2f2890aa
